logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.flywaydb: INFO

server:
  servlet:
    context-path: /v2

spring:
  profiles:
    active: test-integration
  security:
    oauth2:
      resourceserver:
        jwt:
          # Keycloak's JWK Set URI for token validation
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid_connect/certs
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}