services:
  postgres-portal:
    image: postgres:15
    environment:
      POSTGRES_DB: portal_backend
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d portal_backend"]
      interval: 5s
      timeout: 5s
      retries: 10