logging:
  level:
    root: INFO
    org.hibernate: WARN
    org.flywaydb: WARN

server:
  servlet:
    context-path: /v3

spring:
  application:
    name: iot-schema-service
  security:
    oauth2:
      resourceserver:
        jwt:
          # Keycloak's JWK Set URI for token validation
          jwk-set-uri: http://localhost:8080/realms/{realm}/protocol/openid_connect/certs
          # Token issuer validation
          issuer-uri: http://localhost:8080/realms/{realm}


  jpa:
    properties:
      hibernate.format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
    version: openapi-3-1
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
