spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portal_backend?sslmode=disable&gssEncMode=disable # Needs to be overwritten in Production using Env SPRING_DATASOURCE_URL
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
