spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portal_backend
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
