debug: true


logging:
  level:
    root: DEBUG
    org.hibernate: DEBUG
    org.flywaydb: DEBUG


app:
  url: http://localhost:8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/iot_schema  # Port 5434 for app DB
    username: iot
    password: iot

  jpa:
    show-sql: true  # Usually helpful for local development
    hibernate:
      ddl-auto: update  # Local-specific, might want validate/none in other envs

keycloak:
  realm: "iot"
  auth-server-url: http://localhost:8080
