logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.flywaydb: INFO

app:
  url: http://localhost:8089

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true

  # Kafka local deployment settings
  kafka:
    bootstrap-servers: localhost:9092

keycloak:
  realm: "iot"
  auth-server-url: http://localhost:8080

# Kafka Topic Configuration for local
kafka:
  topic-prefix: ""  # Empty for local

