# Gitlab pipeline for portal frontend & backend.
# Integrates custom jobs (blow) and Gitlab templates.
# Publishes results in Gitlab that are shown inside Merge Requests

# Local testing:
# gitlab-ci-local <jobName>

# Change to retrigger all pipeline for a new commit

include:
  - .gitlab/ci/frontend.yml
  - .gitlab/ci/backend.yml
  - .gitlab/ci/config-adapter.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.v2.gitlab-ci.yml
    inputs:
      stage: report
  - template: Jobs/Secret-Detection.gitlab-ci.yml

workflow:
  rules:
    # Always run on main and develop branch
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"
    # Run on merge request branches
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Run on tag events
    - if: $CI_COMMIT_TAG

stages: [lint, test, qa, build, container-qa, deploy, report]

variables:
  GITLAB_ADVANCED_SAST_ENABLED: 'true'
  AST_ENABLE_MR_PIPELINES: 'true' # Enable secret detection in MR pipelines
  DS_ENFORCE_NEW_ANALYZER: 'true'
  DS_MAX_DEPTH: 3

debug-gitlab-features:
  stage: lint
  image: alpine
  script:
    - echo "GITLAB_FEATURES = $GITLAB_FEATURES"
    - echo "CI_COMMIT_BRANCH = $CI_COMMIT_BRANCH"
    - echo "CI_PIPELINE_SOURCE = $CI_PIPELINE_SOURCE"
    - echo "CI_OPEN_MERGE_REQUESTS = $CI_OPEN_MERGE_REQUESTS"
  rules:
    - when: always
