import { AssignmentScope } from './assignments'

// Mirrors backend PermissionName enum (portal-model PermissionName.java)
export const PERMISSION_NAMES = {
  // Tenant administration
  USER_CREATE: 'USER_CREATE',
  USER_READ: 'USER_READ',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_READ: 'ROLE_READ',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
  ASSIGNMENT_CREATE: 'ASSIGNMENT_CREATE',
  ASSIGNMENT_READ: 'ASSIGNMENT_READ',
  ASSIGNMENT_DELETE: 'ASSIGNMENT_DELETE',
  GROUP_CREATE: 'GROUP_CREATE',
  GROUP_READ: 'GROUP_READ',
  GROUP_UPDATE: 'GROUP_UPDATE',
  GROUP_DELETE: 'GROUP_DELETE',
  PERMISSION_READ: 'PERMISSION_READ',
  // Data
  DATASET_CREATE: 'DATASET_CREATE',
  DATASET_READ: 'DATASET_READ',
  DATASET_UPDATE: 'DATASET_UPDATE',
  DATASET_DELETE: 'DATASET_DELETE',
  DATASET_RELEASE: 'DATASET_RELEASE',
  DATASET_PAYLOAD_CREATE: 'DATASET_PAYLOAD_CREATE',
  DATASET_PAYLOAD_READ: 'DATASET_PAYLOAD_READ',
  DATASET_PAYLOAD_UPDATE: 'DATASET_PAYLOAD_UPDATE',
  DATASET_PAYLOAD_DELETE: 'DATASET_PAYLOAD_DELETE',
  DATASOURCE_CREATE: 'DATASOURCE_CREATE',
  DATASOURCE_READ: 'DATASOURCE_READ',
  DATASOURCE_UPDATE: 'DATASOURCE_UPDATE',
  DATASOURCE_DELETE: 'DATASOURCE_DELETE',
  DATASOURCE_RELEASE: 'DATASOURCE_RELEASE',
  DATASTRUCTURE_CREATE: 'DATASTRUCTURE_CREATE',
  DATASTRUCTURE_READ: 'DATASTRUCTURE_READ',
  DATASTRUCTURE_UPDATE: 'DATASTRUCTURE_UPDATE',
  DATASTRUCTURE_DELETE: 'DATASTRUCTURE_DELETE',
  DATASTRUCTURE_RELEASE: 'DATASTRUCTURE_RELEASE',
} as const

export type PermissionName = (typeof PERMISSION_NAMES)[keyof typeof PERMISSION_NAMES]

export type MeAssignment = {
  scopeType: AssignmentScope
  scopeId: string | null
  permissions: PermissionName[]
}

export type CurrentUser = {
  username: string
  email: string
  title: 'MR' | 'MS' | 'OTHER'
  firstName: string
  lastName: string
  assignments: MeAssignment[]
}
