services:
  model-atlas:
    container_name: model-atlas
    image: eclipsefennec/model.atlas:snapshot
    ports:
      - "8086:8080"
    networks:
      - civitas-network
    environment:
      - APICURIO_HOST=apicurio-registry
      - APICURIO_PORT=8080

# --- Apicurio Registry ---
  apicurio-registry:
    container_name: apicurio-registry
    image: apicurio/apicurio-registry:latest-release
    ports:
          - "8087:8080"
    networks:
      - civitas-network
    environment:
      - APICURIO_REST_DELETION_GROUP_ENABLED=true
      - APICURIO_REST_DELETION_ARTIFACT_ENABLED=true
      - APICURIO_REST_DELETION_ARTIFACT-VERSION_ENABLED=true
      - APICURIO_REST_MUTABILITY_ARTIFACT_VERSION_CONTENT_ENABLED=true

  apicurio-registry-ui:
      container_name: apicurio-registry-ui
      image: apicurio/apicurio-registry-ui:latest-release
      ports:
        - "8888:8080"
      networks:
      - civitas-network
      environment:
        - REGISTRY_API_URL=http://localhost:8081/apis/registry/v3


