package de.civitascore.portal.model.entity;

import de.civitascore.portal.model.entity.base.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Represents a distribution endpoint for a {@link DataSet}, describing how the data can be accessed
 * (URL, format, API type). May be linked to an {@link Activity} and a {@link Resource}.
 */
@Entity
@Table(
    name = "distributions",
    indexes = {
      @Index(name = "idx_distribution_resource", columnList = "resource_id"),
      @Index(name = "idx_distribution_dataset", columnList = "dataset_id"),
      @Index(name = "idx_distribution_activity", columnList = "activity_id")
    })
@Getter
@Setter
public class Distribution extends BaseEntity {

  @Column(name = "access_url", columnDefinition = "TEXT")
  private String accessUrl;

  /** API type for the distribution (e.g., "SensorThings"). */
  @Column(name = "api_type", length = 50)
  private String apiType;

  /** Format/media type of the distribution (e.g., "application/json"). */
  @Column(name = "format", length = 100)
  private String format;

  /** Flag indicating if this distribution was auto-generated during dataset publishing. */
  @Column(name = "auto_generated", nullable = false)
  private Boolean autoGenerated = false;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "resource_id")
  private Resource resource;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "dataset_id")
  private DataSet dataSet;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "activity_id")
  private Activity activity;
}
