services:
  apisix:
    image: apache/apisix:3.14.0-debian
    container_name: civitas-apisix
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix_conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9080:9080"
      - "9443:9443"
    networks:
      - civitas-network

networks:
  civitas-network:
    name: civitas-network
    driver: bridge
    external: true
