import { CONNECTOR_TYPES } from '@/const/connectors'

export const CONNECTORS = {
  [CONNECTOR_TYPES.mqtt]: {
    icon: 'radio',
    type: 'input',
    label: 'MQTT',
    color: 'bg-cyan-100 hover:bg-cyan-50 border-cyan-300',
    output: true,
    yamlKey: 'mqtt',
    properties: [
      {
        key: 'urls',
        type: 'textArea',
        label: { label: 'Brokers', labelHint: 'commaSeparated' },
        rows: 3,
        placeholder: 'tcp://localhost:1883',
        defaultValue: '',
        required: true,
      },
      {
        key: 'topics',
        type: 'input',
        label: { label: 'Topics', labelHint: 'commaSeparated' },
        placeholder: 'foo/bar, sensors/#',
        defaultValue: '',
        required: true,
      },
      {
        key: 'client_id',
        type: 'input',
        label: { label: 'Client ID', labelHint: null },
        placeholder: 'optional',
        defaultValue: '',
        required: false,
      },
      {
        key: 'qos',
        type: 'select',
        label: { label: 'QoS', labelHint: null },
        options: ['0', '1', '2'],
        defaultValue: '1',
        required: true,
      },
      {
        key: 'connect_timeout',
        type: 'input',
        expert: true,
        label: { label: 'Connect Timeout', labelHint: null },
        placeholder: '3s',
        defaultValue: '',
        required: false,
      },
      {
        key: 'keepalive',
        type: 'input',
        expert: true,
        label: { label: 'Keepalive', labelHint: null },
        placeholder: '30s',
        defaultValue: '',
        required: false,
      },
      {
        key: 'tls',
        type: 'checkbox',
        expert: true,
        label: { label: 'TLS Enabled', labelHint: null },
        defaultValue: false,
        required: false,
      },
    ],
  },

  [CONNECTOR_TYPES.sql]: {
    icon: 'database',
    type: 'input',
    label: 'SQL',
    color: 'bg-amber-100 hover:bg-amber-50 border-amber-300',
    output: true,
    yamlKey: 'sql_select',
    properties: [
      {
        key: 'driver',
        type: 'select',
        label: { label: 'Driver', labelHint: '' },
        options: [
          'postgres',
          'mysql',
          'clickhouse',
          'mssql',
          'sqlite',
          'oracle',
          'snowflake',
          'trino',
          'gocosmos',
          'spanner',
        ],
        defaultValue: 'postgres',
        required: true,
      },
      {
        key: 'dsn',
        type: 'input',
        label: { label: 'DSN', labelHint: null },
        placeholder: 'Driver-spezifischer Connection String',
        defaultValue: '',
        required: true,
      },
      {
        key: 'table',
        type: 'input',
        label: { label: 'Table', labelHint: null },
        placeholder: 'table',
        defaultValue: '',
        required: true,
      },
      {
        key: 'columns',
        type: 'textArea',
        label: { label: 'Columns', labelHint: 'commaSeparated' },
        rows: 3,
        placeholder: '* oder col1, col2',
        defaultValue: '*',
        required: true,
      },
      {
        key: 'where',
        type: 'input',
        label: { label: 'WHERE', labelHint: null },
        placeholder: 'col = ? AND id > ?',
        defaultValue: '',
        required: false,
      },
      {
        key: 'args_mapping',
        type: 'textArea',
        label: { label: 'Args Mapping (Bloblang)', labelHint: null },
        rows: 3,
        placeholder: '- this.id, now()',
        defaultValue: '',
        required: false,
      },
      {
        key: 'prefix',
        type: 'input',
        expert: true,
        label: { label: 'Prefix SQL', labelHint: null },
        placeholder: 'optional',
        defaultValue: '',
        required: false,
      },
      {
        key: 'suffix',
        type: 'input',
        expert: true,
        label: { label: 'Suffix SQL', labelHint: null },
        placeholder: 'optional',
        defaultValue: '',
        required: false,
      },
      {
        key: 'init_files',
        type: 'textArea',
        expert: true,
        label: { label: 'Init SQL Files', labelHint: 'commaSeparated' },
        rows: 3,
        defaultValue: '',
        required: false,
      },
      {
        key: 'init_statement',
        type: 'textArea',
        expert: true,
        label: { label: 'Init SQL Statement', labelHint: null },
        rows: 4,
        defaultValue: '',
        required: false,
      },
      {
        key: 'conn_max_idle_time',
        type: 'input',
        expert: true,
        label: { label: 'Max Idle Time', labelHint: null },
        placeholder: 'e.g. 5m',
        defaultValue: '',
        required: false,
      },
      {
        key: 'conn_max_life_time',
        type: 'input',
        expert: true,
        label: { label: 'Max Life Time', labelHint: null },
        placeholder: 'e.g. 1h',
        defaultValue: '',
        required: false,
      },
      {
        key: 'conn_max_idle',
        type: 'input',
        expert: true,
        label: { label: 'Max Idle Conns', labelHint: null },
        placeholder: '2',
        defaultValue: 2,
        required: false,
      },
      {
        key: 'conn_max_open',
        type: 'input',
        expert: true,
        label: { label: 'Max Open Conns', labelHint: null },
        placeholder: '0 (unlimited)',
        defaultValue: 0,
        required: false,
      },
    ],
  },
}
