<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.civitas</groupId>
	<artifactId>config-adapter-parent</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>

	<name>Civitas Config Adapter Parent</name>
	<description>Parent POM for Civitas Config Adapter modules</description>

	<licenses>
		<license>
			<name>European Union Public License 1.2</name>
			<url>https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<modules>
		<module>config-adapter-api</module>
		<module>config-adapter-configuration</module>
		<module>event-handler-kafka</module>
		<module>config-adapter-application</module>
		<module>config-adapter-keycloak</module>
		<module>config-adapter-apisix</module>
		<module>config-adapter-examples</module>
	</modules>

	<properties>
		<maven.compiler.source>21</maven.compiler.source>
		<maven.compiler.target>21</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<kafka.version>4.1.1</kafka.version>
		<keycloak.version>26.0.7</keycloak.version>
		<cloudevents.version>3.0.0</cloudevents.version>
		<slf4j.version>2.0.9</slf4j.version>
		<jackson.version>2.16.1</jackson.version>
		<jakarta.ws.rs.version>3.1.0</jakarta.ws.rs.version>
		<jersey.version>3.1.5</jersey.version>
		<commons.configuration2.version>2.11.0</commons.configuration2.version>
		<junit.version>5.10.1</junit.version>
		<mockito.version>5.8.0</mockito.version>
		<testcontainers.version>2.0.2</testcontainers.version>
		<awaitility.version>4.2.2</awaitility.version>
		<jacoco.version>0.8.11</jacoco.version>
		<spotless.version>2.46.1</spotless.version>
		<commons.beanutils.version>1.11.0</commons.beanutils.version>
		<commons.io.version>2.21.0</commons.io.version>
		<commons.lang.version>3.20.0</commons.lang.version>
		<commons.compress.version>1.28.0</commons.compress.version>
  		<lz4.version>1.8.1</lz4.version>
  		<at.yawk.lz4.version>1.10.1</at.yawk.lz4.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<!-- CloudEvents -->
			<dependency>
				<groupId>io.cloudevents</groupId>
				<artifactId>cloudevents-api</artifactId>
				<version>${cloudevents.version}</version>
			</dependency>
			<dependency>
				<groupId>io.cloudevents</groupId>
				<artifactId>cloudevents-kafka</artifactId>
				<version>${cloudevents.version}</version>
			</dependency>
			<dependency>
				<groupId>io.cloudevents</groupId>
				<artifactId>cloudevents-json-jackson</artifactId>
				<version>${cloudevents.version}</version>
			</dependency>

			<!-- Kafka -->
			<dependency>
				<groupId>org.apache.kafka</groupId>
				<artifactId>kafka-clients</artifactId>
				<version>${kafka.version}</version>
			</dependency>

			<!-- Keycloak -->
			<dependency>
				<groupId>org.keycloak</groupId>
				<artifactId>keycloak-admin-client</artifactId>
				<version>${keycloak.version}</version>
			</dependency>

			<!-- Jackson -->
			<dependency>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-databind</artifactId>
				<version>${jackson.version}</version>
			</dependency>
			<dependency>
				<groupId>com.fasterxml.jackson.datatype</groupId>
				<artifactId>jackson-datatype-jsr310</artifactId>
				<version>${jackson.version}</version>
			</dependency>

			<!-- JAX-RS / Jersey -->
			<dependency>
				<groupId>jakarta.ws.rs</groupId>
				<artifactId>jakarta.ws.rs-api</artifactId>
				<version>${jakarta.ws.rs.version}</version>
			</dependency>
			<dependency>
				<groupId>org.glassfish.jersey.core</groupId>
				<artifactId>jersey-client</artifactId>
				<version>${jersey.version}</version>
			</dependency>
			<dependency>
				<groupId>org.glassfish.jersey.inject</groupId>
				<artifactId>jersey-hk2</artifactId>
				<version>${jersey.version}</version>
			</dependency>
			<dependency>
				<groupId>org.glassfish.jersey.media</groupId>
				<artifactId>jersey-media-json-jackson</artifactId>
				<version>${jersey.version}</version>
			</dependency>

			<!-- Apache Commons -->
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-configuration2</artifactId>
				<version>${commons.configuration2.version}</version>
			</dependency>
			<dependency>
				<groupId>commons-beanutils</groupId>
				<artifactId>commons-beanutils</artifactId>
				<version>${commons.beanutils.version}</version>
			</dependency>
			<dependency>
				<groupId>commons-io</groupId>
				<artifactId>commons-io</artifactId>
				<version>${commons.io.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-lang3</artifactId>
				<version>${commons.lang.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-compress</artifactId>
				<version>${commons.compress.version}</version>
			</dependency>

   			<!-- lz4 -->
			<dependency>
				<groupId>org.lz4</groupId>
				<artifactId>lz4-java</artifactId>
				<version>${lz4.version}</version>
			</dependency>
			<dependency>
				<groupId>at.yawk.lz4</groupId>
				<artifactId>lz4-java</artifactId>
				<version>${at.yawk.lz4.version}</version>
			</dependency>

			<!-- Logging -->
			<dependency>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-api</artifactId>
				<version>${slf4j.version}</version>
			</dependency>
			<dependency>
				<groupId>org.slf4j</groupId>
				<artifactId>slf4j-simple</artifactId>
				<version>${slf4j.version}</version>
			</dependency>

			<!-- Testing -->
			<dependency>
				<groupId>org.junit.jupiter</groupId>
				<artifactId>junit-jupiter</artifactId>
				<version>${junit.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.mockito</groupId>
				<artifactId>mockito-core</artifactId>
				<version>${mockito.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.mockito</groupId>
				<artifactId>mockito-junit-jupiter</artifactId>
				<version>${mockito.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.testcontainers</groupId>
				<artifactId>testcontainers</artifactId>
				<version>${testcontainers.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.testcontainers</groupId>
				<artifactId>testcontainers-kafka</artifactId>
				<version>${testcontainers.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.testcontainers</groupId>
				<artifactId>testcontainers-junit-jupiter</artifactId>
				<version>${testcontainers.version}</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.awaitility</groupId>
				<artifactId>awaitility</artifactId>
				<version>${awaitility.version}</version>
				<scope>test</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.11.0</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>3.2.3</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-failsafe-plugin</artifactId>
					<version>3.2.3</version>
				</plugin>
				<plugin>
					<groupId>org.jacoco</groupId>
					<artifactId>jacoco-maven-plugin</artifactId>
					<version>${jacoco.version}</version>
				</plugin>
				<plugin>
					<groupId>com.diffplug.spotless</groupId>
					<artifactId>spotless-maven-plugin</artifactId>
					<version>${spotless.version}</version>
				</plugin>
			</plugins>
		</pluginManagement>
		<plugins>
			<plugin>
				<groupId>com.diffplug.spotless</groupId>
				<artifactId>spotless-maven-plugin</artifactId>
				<configuration>
					<java>
						<includes>
							<include>src/main/java/**/*.java</include>
							<include>src/test/java/**/*.java</include>
						</includes>
						<licenseHeader>
							<content>/**
 * Copyright (c) 2012 - $YEAR Data In Motion and others. All rights reserved.
 *
 * &lt;p&gt;This program and the accompanying materials are made available under the terms of the Eclipse
 * Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * &lt;p&gt;SPDX-License-Identifier: EPL-2.0
 *
 * &lt;p&gt;Contributors: Data In Motion - initial API and implementation
 */</content>
						</licenseHeader>
						<googleJavaFormat />
						<removeUnusedImports />
						<importOrder />
						<formatAnnotations />
					</java>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>check</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>prepare-agent</id>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					<execution>
						<id>report</id>
						<phase>test</phase>
						<goals>
							<goal>report</goal>
						</goals>
						<configuration>
							<formats>
								<format>XML</format>
								<format>CSV</format>
								<format>HTML</format>
							</formats>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
