import { CONNECTOR_TYPES } from '@/types/datasources'

export const NODE_DEFS = {
  [CONNECTOR_TYPES.MQTT]: {
    icon: 'radio',
    type: 'input',
    label: 'MQTT',
    color: 'bg-cyan-100 hover:bg-cyan-50 border-cyan-300',
    output: true,
    yamlKey: 'mqtt',
    properties: [
      {
        key: 'urls',
        type: 'textArea',
        label: 'Brokers (Array)',
        rows: 3,
        placeholder: '- tcp://localhost:1883',
        defaultValue: '[]',
      },
      {
        key: 'topics',
        type: 'input',
        label: 'Topics',
        placeholder: 'foo/bar, sensors/#',
        defaultValue: '',
      },
      {
        key: 'client_id',
        type: 'input',
        label: 'Client ID',
        placeholder: 'optional',
        defaultValue: '',
      },
      {
        key: 'qos',
        type: 'select',
        label: 'QoS',
        options: ['0', '1', '2'],
        defaultValue: '1',
      },
      {
        key: 'connect_timeout',
        type: 'input',
        expert: true,
        label: 'Connect Timeout',
        placeholder: '3s',
        defaultValue: '',
      },
      {
        key: 'keepalive',
        type: 'input',
        expert: true,
        label: 'Keepalive',
        placeholder: '30s',
        defaultValue: '',
      },
      {
        key: 'tls.enabled',
        type: 'checkbox',
        expert: true,
        label: 'TLS Enabled',
        defaultValue: false,
      },
    ],
  },

  [CONNECTOR_TYPES.SQL]: {
    icon: 'database',
    type: 'input',
    label: 'SQL',
    color: 'bg-amber-100 hover:bg-amber-50 border-amber-300',
    output: true,
    yamlKey: 'sql_select',
    properties: [
      {
        key: 'driver',
        type: 'select',
        label: 'Driver',
        options: [
          'postgres',
          'mysql',
          'clickhouse',
          'mssql',
          'sqlite',
          'oracle',
          'snowflake',
          'trino',
          'gocosmos',
          'spanner',
        ],
        defaultValue: '',
      },
      {
        key: 'dsn',
        type: 'input',
        label: 'DSN',
        placeholder: 'Driver-spezifischer Connection String',
        defaultValue: '',
      },
      {
        key: 'table',
        type: 'input',
        label: 'Table',
        placeholder: 'tabelle',
        defaultValue: '',
      },
      {
        key: 'columns',
        type: 'textArea',
        label: 'Columns',
        rows: 3,
        placeholder: '["*"] oder ["col1","col2"]',
        defaultValue: '',
      },
      {
        key: 'where',
        type: 'input',
        label: 'WHERE',
        placeholder: 'col = ? AND id > ?',
        defaultValue: '',
      },
      {
        key: 'args_mapping',
        type: 'textArea',
        label: 'Args Mapping (Bloblang)',
        rows: 3,
        placeholder: '[- this.id, now() ]',
        defaultValue: '',
      },
      {
        key: 'prefix',
        type: 'input',
        expert: true,
        label: 'Prefix SQL',
        placeholder: 'optional',
        defaultValue: '',
      },
      {
        key: 'suffix',
        type: 'input',
        expert: true,
        label: 'Suffix SQL',
        placeholder: 'optional',
        defaultValue: '',
      },
      {
        key: 'init_files',
        type: 'textArea',
        expert: true,
        label: 'Init SQL Files (array)',
        rows: 3,
        defaultValue: '[]',
      },
      {
        key: 'init_statement',
        type: 'textArea',
        expert: true,
        label: 'Init SQL Statement',
        rows: 4,
        defaultValue: '',
      },
      {
        key: 'conn_max_idle_time',
        type: 'input',
        expert: true,
        label: 'Max Idle Time',
        placeholder: 'e.g. 5m',
        defaultValue: '',
      },
      {
        key: 'conn_max_life_time',
        type: 'input',
        expert: true,
        label: 'Max Life Time',
        placeholder: 'e.g. 1h',
        defaultValue: '',
      },
      {
        key: 'conn_max_idle',
        type: 'input',
        expert: true,
        label: 'Max Idle Conns',
        placeholder: '2',
        defaultValue: 2,
      },
      {
        key: 'conn_max_open',
        type: 'input',
        expert: true,
        label: 'Max Open Conns',
        placeholder: '0 (unlimited)',
        defaultValue: 0,
      },
    ],
  },
}
