services:
  postgres-portal:
    image: postgres:15
    environment:
      POSTGRES_DB: iot_schema
      POSTGRES_USER: iot
      POSTGRES_PASSWORD: iot
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iot -d iot_schema"]
      interval: 5s
      timeout: 5s
      retries: 10